package com.dev.heenasupplier.rest

import com.dev.heenasupplier.utils.SharedPreferenceUtility

class APIUtils {
    companion object{
        const val BASE_URL:String = "https://henna.devtechnosys.info/api/manager/"
        const val LOGIN:String = "access/login"
        const val REGISTER:String = "access/register"
        const val FORGOTPASSWORD:String = "access/forget-password"
        const val VERIFYOTP:String = "access/register-verify"
        const val FORGOTPASSVERIFYOTP:String = "access/forget-password-verify"
        const val RESETPASSWORD:String = "access/reset-password"
        const val REGISTERVERIFYRESEND:String = "access/register-verify-resend"
        const val COUNTRIES:String = "option/country"
        const val CATEGORYLIST : String = "option/category"
        const val MEMBERSHIPLIST : String = "membership"
        const val BUYMEMBERSHIP : String = "membership"
        const val LOGOUT : String = "access/logout/{user_id}"
        const val SERVICESLISTING : String = "service/{user_id}"
        const val GALLERYLISTING : String = "gallery"
        const val UPLOADGALLERY : String = "gallery"
        const val DELETEGALLERYIMAGE : String = "gallery/delete/{gallery_id}"
        const val ADDSERVICE : String = "service"
        const val DELETESERVICE = "service/delete/{service_id}"
        const val EDITSERVICE = "service/edit"
        const val GETNOTIFICATIONS = "notification/{user_id}"
        const val ADDOFFERS : String = "offer"
        const val GETOFFERS : String = "offer/{manager_id}"
        const val SHOWOFFER : String = "offer/show/{offer_id}"
        const val SHOWSERVICE : String = "service/show/{sevice_id}"
        const val DELETEOFFER = "offer/delete/{offer_id}"
        const val CONTACTUS : String = "dashboard/contact"
        const val CHANGEPASSWORD : String = "profile/change-password"
        const val SHOWPROFILE : String = "profile/{user_id}"
        const val SHOWCOMMENTS : String = "comment/{user_id}"
        const val UPDATEPROFILE : String = "profile"
        const val ADDEDITBANKS : String = "bank"
        const val SHOWBANKS : String = "bank/{user_id}"
        const val DASHBOARD : String = "dashboard/{user_id}"
        const val BOOKINGLISTING : String = "booking"
        const val ACCEPTBOOKING : String = "booking/accept"
        const val REJECTBOOKING : String = "booking/cancel"
        const val TRANSACTIONSLISTING : String = "transaction/{manager_id}"
        const val SHOWBOOKING : String = "booking/{booking_id}"
        const val SERVICEIMAGEDELETE : String = "service/image/delete/{gallery_id}"
        const val BUYSUBSCRIPTION : String = "subsciptions"
    }
}